<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2aG84xw\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2aG84xw/App_KernelDevContainer.php') {
    touch(__DIR__.'/Container2aG84xw.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\Container2aG84xw\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \Container2aG84xw\App_KernelDevContainer([
    'container.build_hash' => '2aG84xw',
    'container.build_id' => '4b13bf76',
    'container.build_time' => 1644827735,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2aG84xw');
