<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN6bCz8H\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN6bCz8H/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerN6bCz8H.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerN6bCz8H\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerN6bCz8H\App_KernelDevContainer([
    'container.build_hash' => 'N6bCz8H',
    'container.build_id' => 'e3b3bff0',
    'container.build_time' => 1645480560,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN6bCz8H');
