<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEVLeXjj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEVLeXjj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEVLeXjj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEVLeXjj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEVLeXjj\App_KernelDevDebugContainer([
    'container.build_hash' => 'EVLeXjj',
    'container.build_id' => '6f894f70',
    'container.build_time' => 1644829518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEVLeXjj');
